IGNORE: "[ \f\t]*|#[^\n]*";
ARGSSEP: ",\n*";
NUMBER: "-?0|[1-9][0-9]*";
IDENTIFIER: "[^0-9\(\)\n ;,\f\t\-][^\(\)\n ;,\f\t\-]*|;";
TERM: "\n+";
OP: "\(\n*";
CP: "\n*\)";

main: block [EOF];

block: expr [TERM] >block< | expr [TERM]?;
expr: message >expr< | message;
message: symbol arguments?;
arguments: [OP] expr ([ARGSSEP] expr)* [ARGSSEP]? [CP];
symbol: <IDENTIFIER> | <NUMBER>;
